### ISSUE TITLE
mkdocs: convenient copy codeblock to all docs

### ISSUE THREAD

**Issue by River-Mochi** [ltsp/ltsp#817]
Hint
if you add this to mkdocs.yml for example,  it adds a convenient copy icon for people so they can easily copy anything inside a codeblock. it's part of Material mkdocs. it will look like the copy icon you see here to the right side of the codeblock.

```
theme:
  name: material
  features:
    - content.code.copy
```

reference  https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button

just a suggestion
